### PR TITLE
Duplex-stream-based implementation

### LINKED ISSUE #42: Parallel streams using gulp-jasmine prevent tests from all streams from being run.
If one stream is running with gulp-jasmine and another stream uses gulp-jasmine then only the stream that completes first will actually run that streams tests (the tests from the other stream are not run). 

Example test:
```
it('should run all tests when new tests are added while running tests.', function (done) {
	var numTasks = 0;
	var output = '';
	var oldWrite = process.stdout.write;
	process.stdout.write = function (str) {
		output += str;
	};
	var startStream = function() {
		numTasks++;
		var stream = jasmine({
			timeout: 9000,
			verbose: true
		});
		var reader = through2.obj(function (file, enc, cb) {
			cb();
		}, function (cb) {
			process.stdout.write = out;
			assert.equal(output.match(/should pass another test: passed/g).length, 1);
			if (--numTasks <= 0) {
				done();
			}
			cb();
		});

		stream.pipe(reader);

		return stream;
	};

	var otherFixtureStream = startStream();
	var fixtureStream = startStream();


	fixtureStream.write(new gutil.File({
		path: 'fixture.js',
		contents: new Buffer('')
	}));

	otherFixtureStream.write(new gutil.File({
		path: 'otherFixture.js',
		contents: new Buffer('')
	}));

	fixtureStream.end();
	otherFixtureStream.end();
});
```
otherFixture.js:
```
describe('other fixture', function () {
	it('should pass another test', function (done) {
		expect(1).toBe(1);
		done();
	});
});
```

### PR DESCRIPTION
**Pull request by muroc**
Here is an implementation based on `stream.Duplex`. I've tested it with a gulpfile. It's not a full rewrite. I'm making the smallest step possible. Node v0.10 and v0.12 are still supported.

Functional differences:
 1. spec vinyls are passed down the pipeline,
 2. `end` is emitted after jasmine is done running specs.

It resolves #42 and #49.

### CODE REVIEW

**Comment by muroc** [comment]
It works, but I'm having a hard time making ava tests pass. @jbblanchet, could you help me with those?

**Comment by sindresorhus** [comment]
Why couldn't `through2` be used?

> spec vinyls are passed down the stream,

What does this mean exactly?

**Comment by muroc** [comment]
Hi @sindresorhus,

>> spec vinyls are passed down the stream,
> 
>What does this mean exactly?

I ment down the pipeline, I'll correct it.

```js
return gulp.src('fixture.js')
  .pipe(jasmine())
  .pipe(anotherStream())
;
```
During execution of above pipeline, `jasmine` receives a call to [`Writable.write`][write] with a [vinyl][vinyl] object as argument. This vinyl contains spec file (fixture.js). In current master of gulp-jasmine, these vinyls are not passed down the pipeline, which means that `anotherStream`will not receive them. This PR changes that (passing files down the pipeline is done by calling [`Readable.push`][push] in reaction to [`Readable._read`][_read]).

[write]: https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback
[vinyl]: https://github.com/gulpjs/vinyl
[push]: https://nodejs.org/api/stream.htmlstream_readable_push_chunk_encoding
[_read]: https://nodejs.org/api/stream.html#stream_readable_read_size_1

These vinyls could be augmented with test results before passing down the pipeline, which would enable implementing more fine grained control of jasmine in the pipeline.

```js
return gulp.src('fixture.js')
  .pipe(jasmine())
  .pipe(jasmine.report(new MyJasmineReporter()))
  .pipe(jasmine.failAfterError())
;
```
(a topic for another PR)

> Why couldn't `through2` be used?

The idea was that gulp-jasmine should:

1. Run the specs,
2. Pass vinyls down the pipeline,
3. Emit `end` event.

I thought that implementing this order of operation is impossible using `through2` (after reading #77), but your question makes me doubt that assumption. I will try to implement it by using through2 in my first PR.

**Comment by sindresorhus** [comment]
> Pass vinyls down the pipeline,

It already does that: https://github.com/sindresorhus/gulp-jasmine/blob/6e449b4bd35232bee4b5cabe25a87d9f22046936/index.js#L74

**Comment by muroc** [comment]
https://tonicdev.com/muroc/57ae38be110bc91300851b04

Yep, everything seems to be working fine. This PR resolves non-existent problem.

**Pull request closed without merging**
