### PR TITLE
Support for multiple gulp-jasmine streams

### PR DESCRIPTION
**Pull request by muroc**
Hi,

In my project, I wanted to create **multiple gulp-jasmine streams** and merge them with merge-stream. Unfortunately this did not work. It seems that **Jasmine instance uses some global store of loaded specs** (I was unable to find this in jasmine-core's and jasmine-npm's code bases, so don't know for sure). What I know for sure is that when inside _flush method, only last-created stream contains Jasmine instance with proper spec definitions.

This PR is a workaround to make my configuration work. I moved creation of Jasmine object to _flush method, so that no two Jasmine objects live at the same time. To test this, I modified gulpfile.js so that it creates two gulp-jasmine streams and added some checks. It works like a charm :) although I don't like testing if spec executed by reading a flag and it seems that gulp isn't even invoked on Travis.

In my project, I can use my fork, so no pressure, but consider merging my changes.
Also, if you think that I made some mess, I'll be happy to fix it.

Oh, and many thanks for this plugin :)
Cheers!

### CODE REVIEW

**Comment by muroc** [comment]
Just noticed that these changes also makes things like syntax errors or bad imports in specs emited as PluginErrors instead of thrown exceptions.

**Comment by jbblanchet** [comment]
Thanks for the pull request.

I'm surprised that `new Jasmine()` does not return an independent instance, as seems to be the case when I look at their source code. Maybe @amavisca might offer some insight here. I'd like to investigate that side of the issue first to make sure we are using jasmine-npm correctly.

Also, is there a reason for not merging your streams before the call to gulp-jasmine? I assume it's because you have further processing to do on some of them, but I'm curious about your use case.

Thanks.

**Comment by muroc** [comment]
> ...is there a reason for not merging your streams before the call to gulp-jasmine?

Project's build outputs multiple JavaScript files, so main modules get linted, tested and browserified independently. I could run all specs in one stream, but it would add some complexity to the gulpfile and I would loose this information about in which part of the code a problem exists.

**Comment by muroc** [comment]
I belive it resolves #42.

**Comment by muroc** [comment]
Any chance for merging this?

**Comment by jbblanchet** [comment]
I didn't have the time to check if the problem could be corrected in jasmine-node yet, instead of here. I'll try to find the time this weekend. Sorry about that.

**Comment by jbblanchet** [comment]
I just checked the behavior of jasmine-npm, and opened https://github.com/jasmine/jasmine-npm/issues/86. Either it's a bug, and it should be fixed there, or assuming that 2 instances are keeping their own spec lists is wrong, and I'll merge your PR.

**Comment by muroc** [comment]
This PR is still no good for asynchronuous tests...

**Comment by jbblanchet** [comment]
@sindresorhus I had the answer to the jasmine issue at the end of last week and didn't have time to take care of this before leaving on vacation tomorrow morning. If you had the time to take care of it I would appreciate.

The answer from jasmine was basically that even if the library exports a constructor, every test is added to a global object. I feel that while this PR might make conflicts between different streams less frequent, the asynchronous nature of streams make race conditions likely. The only safe way to run 2 test streams might be to make one dependant on the other.

**Comment by jbblanchet** [comment]
Back from my vacation. After thinking about this, I will not merge the pull request. It seems there's no safe way to run 2 jasmine in parallel in the same process, so I will update the gulp-jasmine doc to reflect that. Feel free to comment here if you think otherwise.

**Pull request closed without merging**
