### PR TITLE
Make sure the stream does not end until Jasmine tests are done

### PR DESCRIPTION
**Pull request by charleshansen**
Spawned from issue #49

### CODE REVIEW

**Comment by jbblanchet** [comment]
Thanks for the Pull Request.

I'm leaving on vacation tonight for a week, and I'm not sure I've thought about all the possible issues, but I'll leave my early thoughts.

I'd like to know more about the use case for the change. You mentioned that in the original issue that it was to solve the following problem:
```javascript
gulp.src('*').pipe(jasmine()).pipe(myCleanupCode)`
```

To me, this problem seems like it could be solved by:
```javascript
gulp.src('*').pipe(jasmine()).on('jasmineDone', myCleanupCode)
```
because you don't want to pipe your files to the event.

You mentioned that you had other transform after, but I feel like this should could be solved by:
```javascript
gulp.src('*')
  .pipe(jasmine())
  .pipe(other())
  .on('end', myCleanupCode)
```
because here `end` should be emitted correctly.

So I'm not yet convinced of the necessity of the change. Feel free to contradict me here :smile:. Also, if you have a concrete example that you could share of a scenario where it is needed, it would be helpful.

**Comment by charleshansen** [comment]
I think the reason I can't use your solution is that the `end` event is not always emitted. In my project, if I have fewer than 32 files in `gulp.src`, I will get the `end` event, but as soon as I have at least 32 files, the `end` event stops happening.  Sorry that is a terrible reproduction case, I'll try to get something better when I have a little more time. I think this is exposing the fact that there is a race condition in the stream, which is why the pausing helps.

No huge rush on my side (I'm just using my fork for the moment). Enjoy the vacation.

**Comment by rdy** [comment]
One question on your comment on attaching the jasmineDone event:

Are you expecting the gulp-jasmine-stream to be the sink in a series of transformations? If so your solution attaching the jasmine done event makes sense.

If you aren't making that assumption I would think that gulp-jasmine should respect the end event by delaying it until after jasmine done is fired by the silent reporter.

For maximum flexibility I think I'd prefer it to respect the stream ending in the right way, that way I could pipe other transformations after gulp-jasmine and expect the correct thing to happen. The alternative is that transformations that happen after still run while gulp-jasmine is executing which could cause some problems (spies or stale requires). If you are expecting it more to be the sink of a gulp task then we'd probably wrap gulp-jasmine in a stream that ends only when the jasmine done event is fired in the way you described above. The pause/resume solution seems to work without causing any foreseeable regressions so far, anyways some food for thought.

**Comment by jbblanchet** [comment]
Back from the woods. @rdy I think you raise a fair point about spies. My main concern is to make sure we are using the stream patterns correctly. I've learned from my multiple mistakes that I'll never fully understand streams, and I've never seen that pattern (`pause/resume`) before. 2 things that might help assuage my doubts:

- another example of a library where such a pattern is used;
- an example of a workflow where there's a use for the stream of test files after jasmine.

Thanks.

**Comment by rdy** [comment]
Sounds good, I think it's reasonable to really ensure that the pattern is used correctly. Since gulp-jasmine uses through2 I think it's safe to assume there will always be a pause and resume functions. I'll take a look around, I think merge2 on npm uses a similar pattern to ensure that streams get merged correctly in the order they are passed into the merge. 

I'll try to dig up some other examples.

**Comment by charleshansen** [comment]
@jbblanchet: +1 on never fully understanding streams. 

We don't really need the stream of files itself, it is mostly for the cleanup code. The appeal is that piping the stream into a flush handler is generally safer than using `stream.on` because the pipes clean themselves up better. 

The actual problem is that we chain a bunch of gulp tasks together and the task that uses gulp-jasmine will sometimes fail to properly complete. The tests will still pass, but the next gulp task will never run. This has been a perennial issue for me when chaining asynchronous gulp tasks and one of the lessons is always `pipe`, never use `on`.

I have tried to recreate the original problem in a more controlled setting and it is difficult. It is certainly more than loading more than 32 spec files. I do still think there is a race condition in the stream, but it looks like the right person wins the race most of the time. I'll keep poking at it, but it might be a while before I have the answer.

For what its worth, we have been using `pause` and `resume` in [gulp-jasmine-browser](https://github.com/jasmine/gulp-jasmine-browser) at a similar time as the pull request is adding it in gulp-jasmine. Hopefully @rdy can find more examples.

**Comment by muroc** [comment]
From the documentation of [stream.Readable](https://nodejs.org/api/stream.html#stream_choose_one):
> ### Choose One
> The Readable stream API evolved across multiple Node.js versions and provides multiple methods of consuming stream data. In general, developers should choose one of the methods of consuming data and should never use multiple methods to consume data from a single stream.
> 
> Use of the `readable.pipe()` method is recommended for most users as it has been implemented to provide the easiest way of consuming stream data. Developers that require more fine-grained control over the transfer and generation of data can use the [EventEmitter](https://nodejs.org/api/events.html#events_class_eventemitter) and `readable.pause()`/`readable.resume()` APIs.

It, AFAICT, means that `.pause()`/`.resume()` should not be called on streams that use pipes.

The problem is, IMO, that through2 is not a very suitable base for implementation of modules that perform complex asynchronous operations, as there is no control over when events are emitted from the stream. If I may suggest another approach to this problem, I think it would be better to simply implement a duplex stream (use streams API directly). Low-level approach would assure that `end` event is emitted after tests are done. There would be no need for `jasmineDone` event.

Low-level implementation would also enable piping test results down the stream and implementing reporters as separate stream (like in gulp-eslint).

As it happens, I have such an implementation of gulp-jasmine on my hard drive :) I could create a PR if you also think this is the way to go.

**Comment by muroc** [comment]
I believe it resolves #42

**Comment by jbblanchet** [comment]
@muroc This has nothing to do with through2, but rather with the Stream API. Whatever solution is chosen will be a hack around the fact that in node Streams, the `finish` event is emitted after calling the `_flush` method, and does not wait for the asynchronous callback. This is an unfortunate design decision, but that's the way the API works.

The `jasmineDone` and `end` events are a different problem as they're only emitted if the stream is piped somewhere. See #71. You can also see the discussion there for the reason I've chosen not to implement reporters as a separate stream (mainly because there would be no file to attach certain events like jasmineDone).

I'm not sure I want to reopen the whole debate about the `finish`, `end` and `jasmineDone` events. This appears to work for most scenarios.

**Comment by jbblanchet** [comment]
@charleshansen I'm still not convinced that the use case here (piping to clean up) warrants the merging of the pull request. `on('jasmineDone')` should work for that use case. If it's not, and you have the ability to reproduce the issue, I'd much prefer fixing it. Here's what I'd use:

```javascript
gulp.task('test', done => {
  gulp.src('*.spec.js')
    .pipe(jasmine())
    .on('jasmineDone', () => {
      /* cleanup code */
      done()
    })
})
```

Here `done` cannot be called before `jasmineDone`. I don't see where the race condition would be.

If there's a use case for piping the tests downstream (and I mean piping the files, not using it for cleanup), I'm still open to hearing it.

On the surface it's a simple enough change, but I'm very cautious when messing with the stream workflow. I'm sorry if I'm a little paranoid. Once bitten, twice shy. :sweat_smile:

**Comment by muroc** [comment]
@jbblanchet I can agree on the problem with the `_flush` method, which is part of a `stream.Transform`, and as through2 is based on `stream.Transform`, this is the problem we're facing.

 But I wanted to defend streams API a bit in here, as it is quite rich and provides classes on different levels of abstractions, each of which provide different level of control. `stream.Transform` is a high-level abstraction  and enables lowest level of control. `stream.Readable` and `stream.Writable` are low-level abstractions and enable the high level of control. What I suggest is using `stream.Duplex` (the same level of control as `stream.Readable` and `stream.Writable`). It has no `_flush` method, so mentioned problem does not apply.

> The `jasmineDone` and `end` events are a different problem as they're only emitted if the stream is piped somewhere.

I understand, but what is the purpose of a stream is there is no sink? Gulp guarantees that a stream returned from gulp task will be consumed.

> See #71. You can also see the discussion there for the reason I've chosen not to implement reporters as a separate stream (mainly because there would be no file to attach certain events like jasmineDone).

In #71 I read that you agreed that accepting a solution which is a bit of a workaround, as there is no time to create proper one.

**Comment by jbblanchet** [comment]
@muroc I'm curious to see your solution in a PR. If you want to try your hand a complete rewrite of gulp-jasmine, feel free to drop support for Node 0.10 and 0.12.

**Comment by muroc** [comment]
Created #82. Not a full rewrite, just resolving this problem.

**Comment by charleshansen** [comment]
After further review, it looks like the problem is that somewhere we were listening to the 'finish' event. Without the pause and resume strategy, the 'finish' event is unpredictable. Piping directly into a through with cleanup code in the flush function seems to be working for us  now. It would still be nice if 'finish' worked, but it is not worth breaking anyone else.

**Comment by muroc** [comment]
I thought about this little more and I think that I misunderstood the problem. I was convinced that we're talking about `end` event, a not `finish`. Just ignore all my comments regarding throught2. Sorry about that...

As for the `finish` event. This event is emitted by`stream.Writable` after receiving call to `writable.end()`. It can't wait for any asynchronuous operation to finish. This is not its purpose.

I think that what you need is properly implemented `end` event, which is emitted by `stream.Readable` after passing null to `Readable.push` (which means end of stream, or EOF).

```js
gulp.src('file_a.js', 'file_b.js')
  .pipe(jasmine())
  .on('finish', function() { console.log('finish') })
  .on('data', function(data) { console.log(data.path) })
  .on('end', function() { console.log('end') })
;
```

Running above code on properly implemented stream should produce following output:
```
finish
file_a.js
file_b.js
end
```

**Comment by rdy** [comment]
We've switched from the finish event to the end event explicitly by making sure we attach the cleanup with through2. This solves the problem for us. In some case the finish event would fire before the file that was emitted because of how the silent reporter fires the flush. It is super subtle and does not seem to happen all the time as in your example.

I'm happy without a pause/resume change and just make sure that it is expected for the flush event to potentially happen in a weird order.

**Comment by jbblanchet** [comment]
Happy you guys have found a solution. Closing for now, feel free to comment if you still think this should be merged.

**Pull request closed without merging**
