### PR TITLE
Add option for jasmine.seed

### PR DESCRIPTION
**Pull request by fkloepf**
Adds an option to set a specific seed, see [jasmine docs](https://jasmine.github.io/setup/nodejs.html#--seed)

Needed to debug tests if the random test order fails in a specific case.

// It is my first pull request in this project. If I should add some more information, just ask for it.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The option needs to be documented in the readme.

**Comment by fkloepf** [comment]
I can add a description but as it is part of the [options of jasmine](https://jasmine.github.io/2.8/node.html#section-23) that is already referenced in the [`readme` of this project](https://github.com/sindresorhus/gulp-jasmine#config), I'm not sure if all other options should be mentioned in the `readme` as well.

Should I duplicate the original jasmine documentation or do you want to keep the current style?

**Comment by sindresorhus** [comment]
Keep the current style.

**Comment by sindresorhus** [comment]
> I'm not sure if all other options should be mentioned in the readme as well.

Each option has to be manually added to this plugin, unfortunately. Like you've done now. So we cannot just document all the options or refer to the Jasmine docs.

**Comment by sindresorhus** [comment]
Closing for lack of activity.

**Pull request closed without merging**
